apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp-restricted
rules:
- apiGroups:
  - "extentions"
  resources:
  - podsecuritypolicies
  resourceNames:
  - restricted
  verbs:
  - use

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-restricted
subjects:
- kind: ServiceAccount
  name: restricted-test
  namespace: default
roleRef:
  kind: ClusterRole
  name: psp-restricted
  apiGroup: rbac.authorization.k8s.io