apiVersion: v1
kind: Service
metadata:
  name: frontservice
spec:
  selector:
    app: front
  type: NodePort
  ports:
  - name: http-frontservice
    port: 8080
    protocol: TCP
    targetPort: 8080
