apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-front
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: front:1.0
        ports:
        - containerPort: 8080